[project]
name = "aspireapp01-pyapi01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-monitor-opentelemetry==1.8.9",
    "debugpy==1.8.21",
    "fastapi==0.139.2",
    "python-dotenv==1.2.2",
    "uvicorn[standard]==0.51.0",
]
